[package]
name = "newapp"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
egui_extras = "0.31.1"
mysql = "26.0.0"
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
eframe = "0.31.1"
